import pandas as pd

pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1987.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1987.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1988.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1988.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1989.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1989.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1990.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1990.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1991.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1991.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1992.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1992.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1993.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1993.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1994.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1994.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1995.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1995.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1996.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1996.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1997.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1997.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1998.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1998.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/1999.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/1999.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2000.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2000.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2001.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2001.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2002.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2002.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2003.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2003.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2004.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2004.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2005.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2005.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2006.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2006.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2007.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2007.csv')
pd.DataFrame(pd.read_csv('C:/PDW/Projekt2/Dane/2008.csv.bz2', compression='bz2', encoding='latin-1')).to_csv('C:/PDW/Projekt2/DaneDecompress/2008.csv')